import type { ComponentType } from 'react';
import {
  Activity,
  AlarmClock,
  Apple,
  Baby,
  BadgeDollarSign,
  Bandage,
  Banknote,
  Bath,
  Bed,
  Bell,
  BicepsFlexed,
  Bike,
  BookMarked,
  BookOpen,
  Brain,
  BriefcaseBusiness,
  Brush,
  Cake,
  Calculator,
  Calendar,
  Camera,
  Car,
  ChartColumn,
  ChartLine,
  ChartNoAxesColumn,
  ChartPie,
  Check,
  CircleCheck as CheckCircle,
  ChevronDown,
  CircleCheckBig,
  CircleDollarSign,
  CircleGauge,
  ClipboardCheck,
  ClipboardList,
  Clock,
  CloudSun,
  Code,
  Coffee,
  Coins,
  Contact,
  CookingPot,
  Cross,
  Crown,
  DollarSign,
  Droplets,
  Dumbbell,
  Eye,
  FileText,
  Film,
  Flame,
  FlaskConical,
  Flower,
  Flower2,
  Folder,
  Footprints,
  Gift,
  GlassWater,
  Globe,
  Goal,
  GraduationCap,
  Guitar,
  HandCoins,
  HandHeart,
  Handshake,
  Headphones,
  Heart,
  HeartHandshake,
  HeartPulse,
  Hospital,
  House,
  Inbox,
  Kanban,
  Keyboard,
  Landmark,
  Languages,
  Laptop,
  Leaf,
  LibraryBig,
  Lightbulb,
  ListTodo,
  Mail,
  Map,
  MapPin,
  Medal,
  MessageCircle,
  MessagesSquare,
  Microscope,
  Moon,
  Mountain,
  Music,
  Notebook,
  Palette,
  PenTool,
  Pencil,
  PersonStanding,
  Phone,
  PiggyBank,
  Pill,
  Plane,
  Receipt,
  Repeat,
  Route,
  Salad,
  Scale,
  School,
  Send,
  Share2,
  ShieldPlus,
  Shirt,
  ShoppingBag,
  ShowerHead,
  Smile,
  Soup,
  Sparkles,
  Sprout,
  Stars,
  Stethoscope,
  Store,
  StretchHorizontal,
  Sun,
  Syringe,
  Tablets,
  Target,
  Thermometer,
  Timer,
  TramFront as Train,
  Trees,
  TrendingDown,
  TrendingUp,
  Trophy,
  UserPlus,
  UserRound,
  Users,
  Utensils,
  Volleyball,
  Wallet,
  Watch,
  Waves,
  Wind,
  Workflow,
  Zap,
} from 'lucide-react-native';

export const DEFAULT_LUCIDE_HABIT_ICON = 'BookOpen';

export type LucideIconComponent = ComponentType<{
  color?: string;
  size?: number;
  strokeWidth?: number;
}>;

export type LucideHabitIconCategory =
  | 'Health'
  | 'Fitness'
  | 'Learning'
  | 'Productivity'
  | 'Mindfulness'
  | 'Finance'
  | 'Social'
  | 'Lifestyle';

export const LUCIDE_HABIT_ICON_CATEGORIES: LucideHabitIconCategory[] = [
  'Health',
  'Fitness',
  'Learning',
  'Productivity',
  'Mindfulness',
  'Finance',
  'Social',
  'Lifestyle',
];

export const LucideCheck = Check;
export const LucideChevronDown = ChevronDown;
export const LucideCrown = Crown;

export const LUCIDE_HABIT_ICONS = {
  Activity,
  AlarmClock,
  Apple,
  Baby,
  BadgeDollarSign,
  Bandage,
  Banknote,
  Bath,
  Bed,
  Bell,
  BicepsFlexed,
  Bike,
  BookMarked,
  BookOpen,
  Brain,
  BriefcaseBusiness,
  Brush,
  Cake,
  Calculator,
  Calendar,
  Camera,
  Car,
  ChartColumn,
  ChartLine,
  ChartNoAxesColumn,
  ChartPie,
  CheckCircle,
  CircleCheckBig,
  CircleDollarSign,
  CircleGauge,
  ClipboardCheck,
  ClipboardList,
  Clock,
  CloudSun,
  Code,
  Coffee,
  Coins,
  Contact,
  CookingPot,
  Cross,
  DollarSign,
  Droplets,
  Dumbbell,
  Eye,
  FileText,
  Film,
  Flame,
  FlaskConical,
  Flower,
  Flower2,
  Folder,
  Footprints,
  Gift,
  GlassWater,
  Globe,
  Goal,
  GraduationCap,
  Guitar,
  HandCoins,
  HandHeart,
  Handshake,
  Headphones,
  Heart,
  HeartHandshake,
  HeartPulse,
  Hospital,
  House,
  Inbox,
  Kanban,
  Keyboard,
  Landmark,
  Languages,
  Laptop,
  Leaf,
  LibraryBig,
  Lightbulb,
  ListTodo,
  Mail,
  Map,
  MapPin,
  Medal,
  MessageCircle,
  MessagesSquare,
  Microscope,
  Moon,
  Mountain,
  Music,
  Notebook,
  Palette,
  PenTool,
  Pencil,
  PersonStanding,
  Phone,
  PiggyBank,
  Pill,
  Plane,
  Receipt,
  Repeat,
  Route,
  Salad,
  Scale,
  School,
  Send,
  Share2,
  ShieldPlus,
  Shirt,
  ShoppingBag,
  ShowerHead,
  Smile,
  Soup,
  Sparkles,
  Sprout,
  Stars,
  Stethoscope,
  Store,
  StretchHorizontal,
  Sun,
  Syringe,
  Tablets,
  Target,
  Thermometer,
  Timer,
  Train,
  Trees,
  TrendingDown,
  TrendingUp,
  Trophy,
  UserPlus,
  UserRound,
  Users,
  Utensils,
  Volleyball,
  Wallet,
  Watch,
  Waves,
  Wind,
  Workflow,
  Zap,
} satisfies Record<string, LucideIconComponent>;

export type LucideHabitIconKey = keyof typeof LUCIDE_HABIT_ICONS;

export type LucideHabitIconOption = {
  key: LucideHabitIconKey;
  name: LucideHabitIconKey;
  label: string;
  category: LucideHabitIconCategory;
  categories: LucideHabitIconCategory[];
  keywords: string[];
};

function iconOption(
  key: LucideHabitIconKey,
  label: string,
  category: LucideHabitIconCategory,
  keywords: string[],
  categories: LucideHabitIconCategory[] = [category]
): LucideHabitIconOption {
  return {
    key,
    name: key,
    label,
    category,
    categories,
    keywords,
  };
}

export const LUCIDE_HABIT_ICON_OPTIONS: LucideHabitIconOption[] = [
  iconOption('Pill', 'Pill', 'Health', ['medicine', 'medication', 'supplement', 'vitamin', 'health', 'pill']),
  iconOption('Tablets', 'Tablets', 'Health', ['supplement', 'pills', 'vitamins', 'meds', 'medicine']),
  iconOption('HeartPulse', 'Heart pulse', 'Health', ['heart', 'pulse', 'cardio', 'health', 'doctor']),
  iconOption('Heart', 'Heart', 'Health', ['heart', 'love', 'care', 'health', 'mindfulness'], ['Health', 'Mindfulness', 'Social']),
  iconOption('Stethoscope', 'Stethoscope', 'Health', ['doctor', 'checkup', 'medical', 'clinic', 'health']),
  iconOption('Cross', 'Care', 'Health', ['care', 'medical', 'health', 'first aid', 'cross']),
  iconOption('ShieldPlus', 'Shield plus', 'Health', ['shield', 'protect', 'immunity', 'health', 'safe']),
  iconOption('Thermometer', 'Thermometer', 'Health', ['temperature', 'fever', 'sick', 'health', 'medical']),
  iconOption('Syringe', 'Syringe', 'Health', ['shot', 'vaccine', 'injection', 'medical', 'health']),
  iconOption('Hospital', 'Hospital', 'Health', ['hospital', 'clinic', 'doctor', 'medical', 'health']),
  iconOption('Bandage', 'Bandage', 'Health', ['bandage', 'injury', 'healing', 'first aid', 'health']),
  iconOption('Droplets', 'Droplets', 'Health', ['water', 'hydrate', 'drink', 'drops', 'health']),
  iconOption('GlassWater', 'Water glass', 'Health', ['water', 'glass', 'drink', 'hydrate', 'hydration']),
  iconOption('Apple', 'Apple', 'Health', ['fruit', 'nutrition', 'food', 'healthy', 'diet']),
  iconOption('Salad', 'Salad', 'Health', ['salad', 'nutrition', 'vegetables', 'meal', 'diet']),
  iconOption('Soup', 'Soup', 'Health', ['soup', 'meal', 'food', 'nutrition', 'cooking']),
  iconOption('CookingPot', 'Cooking', 'Health', ['cook', 'cooking', 'meal prep', 'food', 'kitchen'], ['Health', 'Lifestyle']),
  iconOption('ShowerHead', 'Shower', 'Health', ['shower', 'hygiene', 'wash', 'morning', 'clean']),
  iconOption('Bath', 'Bath', 'Health', ['bath', 'hygiene', 'relax', 'self care', 'clean']),
  iconOption('Scale', 'Scale', 'Health', ['weight', 'scale', 'body', 'measure', 'health']),

  iconOption('Dumbbell', 'Dumbbell', 'Fitness', ['gym', 'lift', 'strength', 'workout', 'fitness'], ['Fitness', 'Lifestyle']),
  iconOption('Activity', 'Activity', 'Fitness', ['activity', 'movement', 'exercise', 'health', 'fitness'], ['Fitness', 'Health']),
  iconOption('Bike', 'Bike', 'Fitness', ['cycling', 'cardio', 'bicycle', 'bike', 'fitness'], ['Fitness', 'Lifestyle']),
  iconOption('Footprints', 'Footprints', 'Fitness', ['walk', 'steps', 'run', 'footprints', 'movement']),
  iconOption('Route', 'Route', 'Fitness', ['route', 'run', 'walk', 'path', 'distance']),
  iconOption('Goal', 'Goal', 'Fitness', ['goal', 'target', 'objective', 'progress', 'productivity'], ['Fitness', 'Productivity', 'Finance']),
  iconOption('Target', 'Target', 'Fitness', ['target', 'aim', 'focus', 'goal', 'productivity'], ['Fitness', 'Productivity']),
  iconOption('Trophy', 'Trophy', 'Fitness', ['trophy', 'win', 'achievement', 'goal', 'fitness']),
  iconOption('Medal', 'Medal', 'Fitness', ['medal', 'award', 'achievement', 'race', 'fitness']),
  iconOption('Flame', 'Flame', 'Fitness', ['flame', 'streak', 'burn', 'energy', 'fitness']),
  iconOption('Zap', 'Zap', 'Fitness', ['energy', 'power', 'fast', 'spark', 'fitness']),
  iconOption('Timer', 'Timer', 'Fitness', ['timer', 'time', 'focus', 'interval', 'productivity'], ['Fitness', 'Productivity', 'Lifestyle']),
  iconOption('Watch', 'Watch', 'Fitness', ['watch', 'time', 'tracking', 'steps', 'fitness']),
  iconOption('CircleGauge', 'Gauge', 'Fitness', ['gauge', 'speed', 'measure', 'progress', 'fitness']),
  iconOption('Mountain', 'Mountain', 'Fitness', ['mountain', 'hike', 'climb', 'outdoors', 'fitness']),
  iconOption('Waves', 'Waves', 'Fitness', ['waves', 'swim', 'water', 'ocean', 'mindfulness'], ['Fitness', 'Mindfulness']),
  iconOption('PersonStanding', 'Standing', 'Fitness', ['standing', 'posture', 'body', 'movement', 'fitness']),
  iconOption('StretchHorizontal', 'Stretch', 'Fitness', ['stretch', 'mobility', 'flexibility', 'warmup', 'fitness']),
  iconOption('BicepsFlexed', 'Biceps', 'Fitness', ['biceps', 'strength', 'muscle', 'lift', 'fitness']),
  iconOption('Volleyball', 'Volleyball', 'Fitness', ['volleyball', 'sport', 'team', 'ball', 'fitness']),

  iconOption('BookOpen', 'Book', 'Learning', ['reading', 'book', 'learn', 'study', 'pages'], ['Learning', 'Lifestyle']),
  iconOption('Notebook', 'Notebook', 'Learning', ['notebook', 'notes', 'journal', 'study', 'write']),
  iconOption('Pencil', 'Pencil', 'Learning', ['pencil', 'write', 'draw', 'notes', 'study']),
  iconOption('GraduationCap', 'Graduation cap', 'Learning', ['study', 'school', 'learn', 'education', 'college']),
  iconOption('Brain', 'Brain', 'Learning', ['focus', 'learning', 'mind', 'mental', 'mindfulness'], ['Learning', 'Mindfulness']),
  iconOption('Code', 'Code', 'Learning', ['code', 'programming', 'developer', 'learn', 'computer']),
  iconOption('Laptop', 'Laptop', 'Learning', ['laptop', 'computer', 'work', 'study', 'productivity'], ['Learning', 'Productivity']),
  iconOption('Keyboard', 'Keyboard', 'Learning', ['keyboard', 'typing', 'code', 'write', 'computer']),
  iconOption('Languages', 'Languages', 'Learning', ['language', 'translate', 'words', 'study', 'learn']),
  iconOption('LibraryBig', 'Library', 'Learning', ['library', 'books', 'read', 'study', 'learning']),
  iconOption('School', 'School', 'Learning', ['school', 'class', 'education', 'study', 'learn']),
  iconOption('BookMarked', 'Bookmarked book', 'Learning', ['bookmark', 'book', 'read', 'study', 'learning']),
  iconOption('FileText', 'Document', 'Learning', ['document', 'paper', 'notes', 'read', 'study']),
  iconOption('ClipboardList', 'Checklist', 'Learning', ['checklist', 'clipboard', 'study', 'tasks', 'notes'], ['Learning', 'Productivity']),
  iconOption('Headphones', 'Headphones', 'Learning', ['listen', 'audio', 'podcast', 'music', 'focus'], ['Learning', 'Mindfulness']),
  iconOption('Lightbulb', 'Lightbulb', 'Learning', ['idea', 'learn', 'insight', 'think', 'creative']),
  iconOption('Microscope', 'Microscope', 'Learning', ['science', 'lab', 'biology', 'study', 'research']),
  iconOption('FlaskConical', 'Flask', 'Learning', ['science', 'lab', 'chemistry', 'research', 'supplement']),
  iconOption('Calculator', 'Calculator', 'Learning', ['math', 'calculate', 'numbers', 'finance', 'study'], ['Learning', 'Finance']),
  iconOption('PenTool', 'Pen tool', 'Learning', ['pen', 'write', 'design', 'draw', 'creative']),

  iconOption('ListTodo', 'To-do list', 'Productivity', ['todo', 'task', 'checklist', 'productivity', 'plan']),
  iconOption('Calendar', 'Calendar', 'Productivity', ['schedule', 'plan', 'routine', 'date', 'calendar'], ['Productivity', 'Lifestyle']),
  iconOption('AlarmClock', 'Alarm', 'Productivity', ['alarm', 'clock', 'reminder', 'wake', 'time'], ['Productivity', 'Lifestyle']),
  iconOption('Clock', 'Clock', 'Productivity', ['clock', 'time', 'schedule', 'routine', 'deadline']),
  iconOption('Bell', 'Bell', 'Productivity', ['bell', 'reminder', 'notification', 'alert', 'time']),
  iconOption('BriefcaseBusiness', 'Briefcase', 'Productivity', ['work', 'business', 'briefcase', 'job', 'productivity']),
  iconOption('ClipboardCheck', 'Completed task', 'Productivity', ['done', 'complete', 'task', 'checklist', 'work']),
  iconOption('CheckCircle', 'Check circle', 'Productivity', ['check', 'done', 'complete', 'habit', 'task']),
  iconOption('CircleCheckBig', 'Big check', 'Productivity', ['check', 'complete', 'done', 'success', 'task']),
  iconOption('Repeat', 'Repeat', 'Productivity', ['repeat', 'routine', 'habit', 'recurring', 'loop']),
  iconOption('Workflow', 'Workflow', 'Productivity', ['workflow', 'process', 'system', 'automation', 'productivity']),
  iconOption('Folder', 'Folder', 'Productivity', ['folder', 'organize', 'files', 'work', 'project']),
  iconOption('Inbox', 'Inbox', 'Productivity', ['inbox', 'email', 'organize', 'task', 'work']),
  iconOption('Send', 'Send', 'Productivity', ['send', 'email', 'message', 'share', 'social'], ['Productivity', 'Social']),
  iconOption('Kanban', 'Kanban', 'Productivity', ['kanban', 'board', 'tasks', 'project', 'workflow']),
  iconOption('ChartNoAxesColumn', 'Bar chart', 'Productivity', ['chart', 'bar', 'stats', 'progress', 'analytics']),

  iconOption('Leaf', 'Leaf', 'Mindfulness', ['calm', 'nature', 'mindfulness', 'plant', 'peace'], ['Mindfulness', 'Health']),
  iconOption('Moon', 'Moon', 'Mindfulness', ['sleep', 'night', 'rest', 'moon', 'calm'], ['Mindfulness', 'Health']),
  iconOption('Sun', 'Sun', 'Mindfulness', ['sun', 'morning', 'light', 'outside', 'energy'], ['Mindfulness', 'Health']),
  iconOption('Wind', 'Wind', 'Mindfulness', ['breath', 'wind', 'air', 'calm', 'meditation']),
  iconOption('Sparkles', 'Sparkles', 'Mindfulness', ['sparkle', 'clean', 'magic', 'reset', 'mindfulness'], ['Mindfulness', 'Lifestyle']),
  iconOption('Smile', 'Smile', 'Mindfulness', ['smile', 'happy', 'mood', 'social', 'joy'], ['Mindfulness', 'Social']),
  iconOption('HandHeart', 'Care', 'Mindfulness', ['care', 'kindness', 'self care', 'support', 'social'], ['Mindfulness', 'Social']),
  iconOption('Flower', 'Flower', 'Mindfulness', ['flower', 'nature', 'calm', 'mindfulness', 'beauty']),
  iconOption('Flower2', 'Flower two', 'Mindfulness', ['flower', 'nature', 'calm', 'mindfulness', 'plant']),
  iconOption('Sprout', 'Sprout', 'Mindfulness', ['sprout', 'growth', 'plant', 'nature', 'calm']),
  iconOption('Trees', 'Trees', 'Mindfulness', ['trees', 'forest', 'nature', 'outside', 'lifestyle'], ['Mindfulness', 'Lifestyle']),
  iconOption('CloudSun', 'Cloud sun', 'Mindfulness', ['weather', 'sun', 'cloud', 'outside', 'calm']),
  iconOption('Music', 'Music', 'Mindfulness', ['music', 'song', 'listen', 'practice', 'relax'], ['Mindfulness', 'Lifestyle']),
  iconOption('Stars', 'Stars', 'Mindfulness', ['stars', 'night', 'sparkle', 'sleep', 'calm']),
  iconOption('Eye', 'Eye', 'Mindfulness', ['eye', 'focus', 'observe', 'mindful', 'attention']),

  iconOption('PiggyBank', 'Piggy bank', 'Finance', ['saving', 'money', 'finance', 'budget', 'piggy bank']),
  iconOption('Wallet', 'Wallet', 'Finance', ['budget', 'money', 'spending', 'wallet', 'finance']),
  iconOption('DollarSign', 'Dollar', 'Finance', ['dollar', 'money', 'cash', 'finance', 'income']),
  iconOption('Banknote', 'Banknote', 'Finance', ['cash', 'money', 'banknote', 'finance', 'pay']),
  iconOption('Landmark', 'Bank', 'Finance', ['bank', 'finance', 'landmark', 'saving', 'money']),
  iconOption('Receipt', 'Receipt', 'Finance', ['receipt', 'expense', 'spending', 'budget', 'finance']),
  iconOption('ChartLine', 'Line chart', 'Finance', ['chart', 'line', 'growth', 'invest', 'finance']),
  iconOption('ChartPie', 'Pie chart', 'Finance', ['chart', 'pie', 'budget', 'finance', 'split']),
  iconOption('ChartColumn', 'Column chart', 'Finance', ['chart', 'bar', 'stats', 'finance', 'analytics']),
  iconOption('Coins', 'Coins', 'Finance', ['coins', 'money', 'cash', 'saving', 'finance']),
  iconOption('HandCoins', 'Hand coins', 'Finance', ['coins', 'money', 'pay', 'income', 'finance']),
  iconOption('BadgeDollarSign', 'Money badge', 'Finance', ['money', 'badge', 'dollar', 'finance', 'reward']),
  iconOption('CircleDollarSign', 'Dollar circle', 'Finance', ['money', 'dollar', 'circle', 'finance', 'cash']),
  iconOption('Store', 'Store', 'Finance', ['store', 'business', 'shop', 'finance', 'sales']),
  iconOption('TrendingUp', 'Trending up', 'Finance', ['growth', 'increase', 'invest', 'trend', 'finance']),
  iconOption('TrendingDown', 'Trending down', 'Finance', ['decrease', 'budget', 'trend', 'finance', 'spending']),

  iconOption('Users', 'Users', 'Social', ['friends', 'family', 'social', 'group', 'people']),
  iconOption('UserRound', 'Person', 'Social', ['person', 'user', 'profile', 'social', 'self']),
  iconOption('MessageCircle', 'Message', 'Social', ['message', 'chat', 'talk', 'social', 'communication']),
  iconOption('MessagesSquare', 'Messages', 'Social', ['messages', 'chat', 'conversation', 'social', 'communication']),
  iconOption('Phone', 'Phone', 'Social', ['phone', 'call', 'talk', 'social', 'contact']),
  iconOption('Mail', 'Mail', 'Social', ['mail', 'email', 'letter', 'message', 'social']),
  iconOption('HeartHandshake', 'Support', 'Social', ['support', 'help', 'care', 'relationship', 'social']),
  iconOption('Gift', 'Gift', 'Social', ['gift', 'birthday', 'present', 'social', 'celebrate']),
  iconOption('Cake', 'Cake', 'Social', ['cake', 'birthday', 'celebrate', 'party', 'social']),
  iconOption('House', 'Home', 'Social', ['home', 'house', 'family', 'lifestyle', 'routine'], ['Social', 'Lifestyle']),
  iconOption('Baby', 'Baby', 'Social', ['baby', 'child', 'family', 'care', 'social']),
  iconOption('Contact', 'Contact', 'Social', ['contact', 'address', 'person', 'social', 'network']),
  iconOption('UserPlus', 'Add person', 'Social', ['friend', 'add', 'person', 'social', 'meet']),
  iconOption('Share2', 'Share', 'Social', ['share', 'send', 'social', 'network', 'connect']),
  iconOption('Handshake', 'Handshake', 'Social', ['handshake', 'agreement', 'support', 'social', 'meet']),
  iconOption('Globe', 'Globe', 'Social', ['world', 'global', 'community', 'travel', 'social']),

  iconOption('Coffee', 'Coffee', 'Lifestyle', ['coffee', 'morning', 'cafe', 'drink', 'routine']),
  iconOption('Bed', 'Bed', 'Lifestyle', ['bed', 'sleep', 'rest', 'night', 'routine'], ['Lifestyle', 'Health']),
  iconOption('Guitar', 'Guitar', 'Lifestyle', ['guitar', 'music', 'instrument', 'hobby', 'practice']),
  iconOption('Palette', 'Palette', 'Lifestyle', ['art', 'paint', 'creative', 'color', 'hobby']),
  iconOption('Brush', 'Brush', 'Lifestyle', ['brush', 'paint', 'art', 'creative', 'clean']),
  iconOption('Camera', 'Camera', 'Lifestyle', ['photo', 'camera', 'picture', 'creative', 'memory']),
  iconOption('Plane', 'Plane', 'Lifestyle', ['travel', 'flight', 'trip', 'plane', 'vacation']),
  iconOption('Car', 'Car', 'Lifestyle', ['car', 'drive', 'commute', 'travel', 'errand']),
  iconOption('Train', 'Train', 'Lifestyle', ['train', 'transport', 'commute', 'travel', 'trip']),
  iconOption('Map', 'Map', 'Lifestyle', ['map', 'travel', 'route', 'plan', 'outside']),
  iconOption('MapPin', 'Location', 'Lifestyle', ['location', 'pin', 'place', 'travel', 'map']),
  iconOption('Shirt', 'Shirt', 'Lifestyle', ['clothes', 'shirt', 'laundry', 'style', 'outfit']),
  iconOption('Utensils', 'Utensils', 'Lifestyle', ['food', 'eat', 'meal', 'restaurant', 'kitchen']),
  iconOption('ShoppingBag', 'Shopping bag', 'Lifestyle', ['shopping', 'bag', 'store', 'errand', 'purchase']),
  iconOption('Film', 'Film', 'Lifestyle', ['movie', 'film', 'watch', 'cinema', 'hobby']),
];

export function getLucideHabitIcon(iconValue: string | null | undefined) {
  if (iconValue && iconValue in LUCIDE_HABIT_ICONS) {
    return LUCIDE_HABIT_ICONS[iconValue as LucideHabitIconKey];
  }

  return LUCIDE_HABIT_ICONS[DEFAULT_LUCIDE_HABIT_ICON];
}
